var senators = [
    {
      "member_full": "Alexander (R-TN)",
      "last_name": "Alexander",
      "first_name": "Lamar",
      "party": "R",
      "state": "TN",
      "address": "455 Dirksen Senate Office Building",
      "phone": "(202) 224-4944",
      "email": "http://www.alexander.senate.gov/public/index.cfm?p=Email",
      "website": "http://www.alexander.senate.gov/",
      "class": "Class II",
      "bioguide_id": "A000360"
    },
    {
      "member_full": "Baldwin (D-WI)",
      "last_name": "Baldwin",
      "first_name": "Tammy",
      "party": "D",
      "state": "WI",
      "address": "709 Hart Senate Office Building",
      "phone": "(202) 224-5653",
      "email": "https://www.baldwin.senate.gov/feedback",
      "website": "http://www.baldwin.senate.gov/",
      "class": "Class I",
      "bioguide_id": "B001230"
    },
    {
      "member_full": "Barrasso (R-WY)",
      "last_name": "Barrasso",
      "first_name": "John",
      "party": "R",
      "state": "WY",
      "address": "307 Dirksen Senate Office Building",
      "phone": "(202) 224-6441",
      "email": "https://www.barrasso.senate.gov/public/index.cfm/contact-form",
      "website": "http://www.barrasso.senate.gov",
      "class": "Class I",
      "bioguide_id": "B001261"
    },
    {
      "member_full": "Bennet (D-CO)",
      "last_name": "Bennet",
      "first_name": "Michael F.",
      "party": "D",
      "state": "CO",
      "address": "261 Russell Senate Office Building",
      "phone": "(202) 224-5852",
      "email": "https://www.bennet.senate.gov/?p=contact",
      "website": "http://www.bennet.senate.gov",
      "class": "Class III",
      "bioguide_id": "B001267"
    },
    {
      "member_full": "Blumenthal (D-CT)",
      "last_name": "Blumenthal",
      "first_name": "Richard",
      "party": "D",
      "state": "CT",
      "address": "706 Hart Senate Office Building",
      "phone": "(202) 224-2823",
      "email": "https://www.blumenthal.senate.gov/contact/",
      "website": "http://www.blumenthal.senate.gov",
      "class": "Class III",
      "bioguide_id": "B001277"
    },
    {
      "member_full": "Blunt (R-MO)",
      "last_name": "Blunt",
      "first_name": "Roy",
      "party": "R",
      "state": "MO",
      "address": "260 Russell Senate Office Building",
      "phone": "(202) 224-5721",
      "email": "https://www.blunt.senate.gov/public/index.cfm/contact-roy",
      "website": "http://www.blunt.senate.gov",
      "class": "Class III",
      "bioguide_id": "B000575"
    },
    {
      "member_full": "Booker (D-NJ)",
      "last_name": "Booker",
      "first_name": "Cory A.",
      "party": "D",
      "state": "NJ",
      "address": "359 Dirksen Senate Office Building",
      "phone": "(202) 224-3224",
      "email": "https://www.booker.senate.gov/?p=contact",
      "website": "http://www.booker.senate.gov",
      "class": "Class II",
      "bioguide_id": "B001288"
    },
    {
      "member_full": "Boozman (R-AR)",
      "last_name": "Boozman",
      "first_name": "John",
      "party": "R",
      "state": "AR",
      "address": "141 Hart Senate Office Building",
      "phone": "(202) 224-4843",
      "email": "https://www.boozman.senate.gov/public/index.cfm/contact",
      "website": "http://www.boozman.senate.gov/",
      "class": "Class III",
      "bioguide_id": "B001236"
    },
    {
      "member_full": "Brown (D-OH)",
      "last_name": "Brown",
      "first_name": "Sherrod",
      "party": "D",
      "state": "OH",
      "address": "713 Hart Senate Office Building",
      "phone": "(202) 224-2315",
      "email": "http://www.brown.senate.gov/contact/",
      "website": "http://www.brown.senate.gov/",
      "class": "Class I",
      "bioguide_id": "B000944"
    },
    {
      "member_full": "Burr (R-NC)",
      "last_name": "Burr",
      "first_name": "Richard",
      "party": "R",
      "state": "NC",
      "address": "217 Russell Senate Office Building",
      "phone": "(202) 224-3154",
      "email": "https://www.burr.senate.gov/contact/email",
      "website": "http://www.burr.senate.gov",
      "class": "Class III",
      "bioguide_id": "B001135"
    },
    {
      "member_full": "Cantwell (D-WA)",
      "last_name": "Cantwell",
      "first_name": "Maria",
      "party": "D",
      "state": "WA",
      "address": "511 Hart Senate Office Building",
      "phone": "(202) 224-3441",
      "email": "http://www.cantwell.senate.gov/public/index.cfm/email-maria",
      "website": "http://www.cantwell.senate.gov",
      "class": "Class I",
      "bioguide_id": "C000127"
    },
    {
      "member_full": "Capito (R-WV)",
      "last_name": "Capito",
      "first_name": "Shelley Moore",
      "party": "R",
      "state": "WV",
      "address": "172 Russell Senate Office Building",
      "phone": "(202) 224-6472",
      "email": "https://www.capito.senate.gov/contact/contact-shelley",
      "website": "http://www.capito.senate.gov",
      "class": "Class II",
      "bioguide_id": "C001047"
    },
    {
      "member_full": "Cardin (D-MD)",
      "last_name": "Cardin",
      "first_name": "Benjamin L.",
      "party": "D",
      "state": "MD",
      "address": "509 Hart Senate Office Building",
      "phone": "(202) 224-4524",
      "email": "http://www.cardin.senate.gov/contact/",
      "website": "http://www.cardin.senate.gov/",
      "class": "Class I",
      "bioguide_id": "C000141"
    },
    {
      "member_full": "Carper (D-DE)",
      "last_name": "Carper",
      "first_name": "Thomas R.",
      "party": "D",
      "state": "DE",
      "address": "513 Hart Senate Office Building",
      "phone": "(202) 224-2441",
      "email": "http://www.carper.senate.gov/public/index.cfm/email-senator-carper",
      "website": "http://www.carper.senate.gov",
      "class": "Class I",
      "bioguide_id": "C000174"
    },
    {
      "member_full": "Casey (D-PA)",
      "last_name": "Casey",
      "first_name": "Robert P., Jr.",
      "party": "D",
      "state": "PA",
      "address": "393 Russell Senate Office Building",
      "phone": "(202) 224-6324",
      "email": "https://www.casey.senate.gov/contact/",
      "website": "http://www.casey.senate.gov/",
      "class": "Class I",
      "bioguide_id": "C001070"
    },
    {
      "member_full": "Cassidy (R-LA)",
      "last_name": "Cassidy",
      "first_name": "Bill",
      "party": "R",
      "state": "LA",
      "address": "520 Hart Senate Office Building",
      "phone": "(202) 224-5824",
      "email": "https://www.cassidy.senate.gov/contact",
      "website": "http://www.cassidy.senate.gov",
      "class": "Class II",
      "bioguide_id": "C001075"
    },
    {
      "member_full": "Cochran (R-MS)",
      "last_name": "Cochran",
      "first_name": "Thad",
      "party": "R",
      "state": "MS",
      "address": "113 Dirksen Senate Office Building",
      "phone": "(202) 224-5054",
      "email": "https://www.cochran.senate.gov/public/index.cfm/email-me",
      "website": "http://www.cochran.senate.gov",
      "class": "Class II",
      "bioguide_id": "C000567"
    },
    {
      "member_full": "Collins (R-ME)",
      "last_name": "Collins",
      "first_name": "Susan M.",
      "party": "R",
      "state": "ME",
      "address": "413 Dirksen Senate Office Building",
      "phone": "(202) 224-2523",
      "email": "http://www.collins.senate.gov/contact",
      "website": "http://www.collins.senate.gov",
      "class": "Class II",
      "bioguide_id": "C001035"
    },
    {
      "member_full": "Coons (D-DE)",
      "last_name": "Coons",
      "first_name": "Christopher A.",
      "party": "D",
      "state": "DE",
      "address": "127A Russell Senate Office Building",
      "phone": "(202) 224-5042",
      "email": "https://www.coons.senate.gov/contact",
      "website": "http://www.coons.senate.gov/",
      "class": "Class II",
      "bioguide_id": "C001088"
    },
    {
      "member_full": "Corker (R-TN)",
      "last_name": "Corker",
      "first_name": "Bob",
      "party": "R",
      "state": "TN",
      "address": "425 Dirksen Senate Office Building",
      "phone": "(202) 224-3344",
      "email": "https://www.corker.senate.gov/public/index.cfm/emailme",
      "website": "http://www.corker.senate.gov/",
      "class": "Class I",
      "bioguide_id": "C001071"
    },
    {
      "member_full": "Cornyn (R-TX)",
      "last_name": "Cornyn",
      "first_name": "John",
      "party": "R",
      "state": "TX",
      "address": "517 Hart Senate Office Building",
      "phone": "(202) 224-2934",
      "email": "https://www.cornyn.senate.gov/contact",
      "website": "http://www.cornyn.senate.gov/",
      "class": "Class II",
      "bioguide_id": "C001056",
      "leadership_position": "Assistant Majority Leader"
    },
    {
      "member_full": "Cortez Masto (D-NV)",
      "last_name": "Cortez Masto",
      "first_name": "Catherine",
      "party": "D",
      "state": "NV",
      "address": "B40A Dirksen Senate Office Building",
      "phone": "(202) 224-3542",
      "email": "https://www.cortezmasto.senate.gov/content/contact-senator",
      "website": "http://www.cortezmasto.senate.gov",
      "class": "Class III",
      "bioguide_id": "C001113"
    },
    {
      "member_full": "Cotton (R-AR)",
      "last_name": "Cotton",
      "first_name": "Tom",
      "party": "R",
      "state": "AR",
      "address": "124 Russell Senate Office Building",
      "phone": "(202) 224-2353",
      "email": "http://www.cotton.senate.gov/?p=contact",
      "website": "http://www.cotton.senate.gov",
      "class": "Class II",
      "bioguide_id": "C001095"
    },
    {
      "member_full": "Crapo (R-ID)",
      "last_name": "Crapo",
      "first_name": "Mike",
      "party": "R",
      "state": "ID",
      "address": "239 Dirksen Senate Office Building",
      "phone": "(202) 224-6142",
      "email": "http://www.crapo.senate.gov/contact/email.cfm",
      "website": "http://www.crapo.senate.gov",
      "class": "Class III",
      "bioguide_id": "C000880"
    },
    {
      "member_full": "Cruz (R-TX)",
      "last_name": "Cruz",
      "first_name": "Ted",
      "party": "R",
      "state": "TX",
      "address": "404 Russell Senate Office Building",
      "phone": "(202) 224-5922",
      "email": "http://www.cruz.senate.gov/?p=email_senator",
      "website": "http://www.cruz.senate.gov",
      "class": "Class I",
      "bioguide_id": "C001098"
    },
    {
      "member_full": "Daines (R-MT)",
      "last_name": "Daines",
      "first_name": "Steve",
      "party": "R",
      "state": "MT",
      "address": "320 Hart Senate Office Building",
      "phone": "(202) 224-2651",
      "email": "https://www.daines.senate.gov/connect/email-steve",
      "website": "http://www.daines.senate.gov",
      "class": "Class II",
      "bioguide_id": "D000618"
    },
    {
      "member_full": "Donnelly (D-IN)",
      "last_name": "Donnelly",
      "first_name": "Joe",
      "party": "D",
      "state": "IN",
      "address": "720 Hart Senate Office Building",
      "phone": "(202) 224-4814",
      "email": "https://www.donnelly.senate.gov/contact/email-joe",
      "website": "http://www.donnelly.senate.gov",
      "class": "Class I",
      "bioguide_id": "D000607"
    },
    {
      "member_full": "Duckworth (D-IL)",
      "last_name": "Duckworth",
      "first_name": "Tammy",
      "party": "D",
      "state": "IL",
      "address": "G12 Dirksen Senate Office Building",
      "phone": "(202) 224-2854",
      "email": "https://www.duckworth.senate.gov/content/contact-senator",
      "website": "http://www.duckworth.senate.gov",
      "class": "Class III",
      "bioguide_id": "D000622"
    },
    {
      "member_full": "Durbin (D-IL)",
      "last_name": "Durbin",
      "first_name": "Richard J.",
      "party": "D",
      "state": "IL",
      "address": "711 Hart Senate Office Building",
      "phone": "(202) 224-2152",
      "email": "https://www.durbin.senate.gov/contact/",
      "website": "http://www.durbin.senate.gov",
      "class": "Class II",
      "bioguide_id": "D000563",
      "leadership_position": "Whip"
    },
    {
      "member_full": "Enzi (R-WY)",
      "last_name": "Enzi",
      "first_name": "Michael B.",
      "party": "R",
      "state": "WY",
      "address": "379A Russell Senate Office Building",
      "phone": "(202) 224-3424",
      "email": "http://www.enzi.senate.gov/public/index.cfm/contact?p=e-mail-senator-enzi",
      "website": "http://www.enzi.senate.gov",
      "class": "Class II",
      "bioguide_id": "E000285"
    },
    {
      "member_full": "Ernst (R-IA)",
      "last_name": "Ernst",
      "first_name": "Joni",
      "party": "R",
      "state": "IA",
      "address": "111 Russell Senate Office Building",
      "phone": "(202) 224-3254",
      "email": "https://www.ernst.senate.gov/public/index.cfm/contact",
      "website": "http://www.ernst.senate.gov",
      "class": "Class II",
      "bioguide_id": "E000295"
    },
    {
      "member_full": "Feinstein (D-CA)",
      "last_name": "Feinstein",
      "first_name": "Dianne",
      "party": "D",
      "state": "CA",
      "address": "331 Hart Senate Office Building",
      "phone": "(202) 224-3841",
      "email": "https://www.feinstein.senate.gov/public/index.cfm/e-mail-me",
      "website": "http://www.feinstein.senate.gov",
      "class": "Class I",
      "bioguide_id": "F000062"
    },
    {
      "member_full": "Fischer (R-NE)",
      "last_name": "Fischer",
      "first_name": "Deb",
      "party": "R",
      "state": "NE",
      "address": "454 Russell Senate Office Building",
      "phone": "(202) 224-6551",
      "email": "http://www.fischer.senate.gov/public/index.cfm/contact",
      "website": "http://www.fischer.senate.gov",
      "class": "Class I",
      "bioguide_id": "F000463"
    },
    {
      "member_full": "Flake (R-AZ)",
      "last_name": "Flake",
      "first_name": "Jeff",
      "party": "R",
      "state": "AZ",
      "address": "413 Russell Senate Office Building",
      "phone": "(202) 224-4521",
      "email": "https://www.flake.senate.gov/public/index.cfm/contact-jeff",
      "website": "http://www.flake.senate.gov",
      "class": "Class I",
      "bioguide_id": "F000444"
    },
    {
      "member_full": "Franken (D-MN)",
      "last_name": "Franken",
      "first_name": "Al",
      "party": "D",
      "state": "MN",
      "address": "309 Hart Senate Office Building",
      "phone": "(202) 224-5641",
      "email": "https://www.franken.senate.gov/?p=contact",
      "website": "http://www.franken.senate.gov",
      "class": "Class II",
      "bioguide_id": "F000457"
    },
    {
      "member_full": "Gardner (R-CO)",
      "last_name": "Gardner",
      "first_name": "Cory",
      "party": "R",
      "state": "CO",
      "address": "354 Russell Senate Office Building",
      "phone": "(202) 224-5941",
      "email": "https://www.gardner.senate.gov/contact-cory/email-cory",
      "website": "http://www.gardner.senate.gov",
      "class": "Class II",
      "bioguide_id": "G000562"
    },
    {
      "member_full": "Gillibrand (D-NY)",
      "last_name": "Gillibrand",
      "first_name": "Kirsten E.",
      "party": "D",
      "state": "NY",
      "address": "478 Russell Senate Office Building",
      "phone": "(202) 224-4451",
      "email": "http://www.gillibrand.senate.gov/contact/",
      "website": "http://www.gillibrand.senate.gov",
      "class": "Class I",
      "bioguide_id": "G000555"
    },
    {
      "member_full": "Graham (R-SC)",
      "last_name": "Graham",
      "first_name": "Lindsey",
      "party": "R",
      "state": "SC",
      "address": "290 Russell Senate Office Building",
      "phone": "(202) 224-5972",
      "email": "https://www.lgraham.senate.gov/public/index.cfm/e-mail-senator-graham",
      "website": "http://www.lgraham.senate.gov/",
      "class": "Class II",
      "bioguide_id": "G000359"
    },
    {
      "member_full": "Grassley (R-IA)",
      "last_name": "Grassley",
      "first_name": "Chuck",
      "party": "R",
      "state": "IA",
      "address": "135 Hart Senate Office Building",
      "phone": "(202) 224-3744",
      "email": "http://www.grassley.senate.gov/contact",
      "website": "http://www.grassley.senate.gov",
      "class": "Class III",
      "bioguide_id": "G000386"
    },
    {
      "member_full": "Harris (D-CA)",
      "last_name": "Harris",
      "first_name": "Kamala D.",
      "party": "D",
      "state": "CA",
      "address": "112 Hart Senate Office Building",
      "phone": "(202) 224-3553",
      "email": "https://www.harris.senate.gov/content/contact-senator",
      "website": "http://www.harris.senate.gov",
      "class": "Class III",
      "bioguide_id": "H001075"
    },
    {
      "member_full": "Hassan (D-NH)",
      "last_name": "Hassan",
      "first_name": "Margaret Wood",
      "party": "D",
      "state": "NH",
      "address": "B85 Russell Senate Office Building",
      "phone": "(202) 224-3324",
      "email": "https://www.hassan.senate.gov/content/contact-senator",
      "website": "http://www.hassan.senate.gov",
      "class": "Class III",
      "bioguide_id": "H001076"
    },
    {
      "member_full": "Hatch (R-UT)",
      "last_name": "Hatch",
      "first_name": "Orrin G.",
      "party": "R",
      "state": "UT",
      "address": "104 Hart Senate Office Building",
      "phone": "(202) 224-5251",
      "email": "http://www.hatch.senate.gov/public/index.cfm/contact?p=Email-Orrin",
      "website": "http://www.hatch.senate.gov/",
      "class": "Class I",
      "bioguide_id": "H000338",
      "leadership_position": "President Pro Tempore"
    },
    {
      "member_full": "Heinrich (D-NM)",
      "last_name": "Heinrich",
      "first_name": "Martin",
      "party": "D",
      "state": "NM",
      "address": "303 Hart Senate Office Building",
      "phone": "(202) 224-5521",
      "email": "http://www.heinrich.senate.gov/contact",
      "website": "http://www.heinrich.senate.gov/",
      "class": "Class I",
      "bioguide_id": "H001046"
    },
    {
      "member_full": "Heitkamp (D-ND)",
      "last_name": "Heitkamp",
      "first_name": "Heidi",
      "party": "D",
      "state": "ND",
      "address": "110 Hart Senate Office Building",
      "phone": "(202) 224-2043",
      "email": "http://www.heitkamp.senate.gov/public/index.cfm/contact",
      "website": "http://www.heitkamp.senate.gov/",
      "class": "Class I",
      "bioguide_id": "H001069"
    },
    {
      "member_full": "Heller (R-NV)",
      "last_name": "Heller",
      "first_name": "Dean",
      "party": "R",
      "state": "NV",
      "address": "324 Hart Senate Office Building",
      "phone": "(202) 224-6244",
      "email": "http://www.heller.senate.gov/public/index.cfm/contact-form",
      "website": "http://www.heller.senate.gov/",
      "class": "Class I",
      "bioguide_id": "H001041"
    },
    {
      "member_full": "Hirono (D-HI)",
      "last_name": "Hirono",
      "first_name": "Mazie K.",
      "party": "D",
      "state": "HI",
      "address": "730 Hart Senate Office Building",
      "phone": "(202) 224-6361",
      "email": "https://www.hirono.senate.gov/contact",
      "website": "http://www.hirono.senate.gov/",
      "class": "Class I",
      "bioguide_id": "H001042"
    },
    {
      "member_full": "Hoeven (R-ND)",
      "last_name": "Hoeven",
      "first_name": "John",
      "party": "R",
      "state": "ND",
      "address": "338 Russell Senate Office Building",
      "phone": "(202) 224-2551",
      "email": "http://www.hoeven.senate.gov/public/index.cfm/email-the-senator",
      "website": "http://www.hoeven.senate.gov",
      "class": "Class III",
      "bioguide_id": "H001061"
    },
    {
      "member_full": "Inhofe (R-OK)",
      "last_name": "Inhofe",
      "first_name": "James M.",
      "party": "R",
      "state": "OK",
      "address": "205 Russell Senate Office Building",
      "phone": "(202) 224-4721",
      "email": "https://www.inhofe.senate.gov/contact",
      "website": "http://www.inhofe.senate.gov/",
      "class": "Class II",
      "bioguide_id": "I000024"
    },
    {
      "member_full": "Isakson (R-GA)",
      "last_name": "Isakson",
      "first_name": "Johnny",
      "party": "R",
      "state": "GA",
      "address": "131 Russell Senate Office Building",
      "phone": "(202) 224-3643",
      "email": "https://www.isakson.senate.gov/public/index.cfm/email-me",
      "website": "http://www.isakson.senate.gov",
      "class": "Class III",
      "bioguide_id": "I000055"
    },
    {
      "member_full": "Johnson (R-WI)",
      "last_name": "Johnson",
      "first_name": "Ron",
      "party": "R",
      "state": "WI",
      "address": "328 Hart Senate Office Building",
      "phone": "(202) 224-5323",
      "email": "https://www.ronjohnson.senate.gov/public/index.cfm/email-the-senator",
      "website": "http://www.ronjohnson.senate.gov/",
      "class": "Class III",
      "bioguide_id": "J000293"
    },
    {
      "member_full": "Kaine (D-VA)",
      "last_name": "Kaine",
      "first_name": "Tim",
      "party": "D",
      "state": "VA",
      "address": "231 Russell Senate Office Building",
      "phone": "(202) 224-4024",
      "email": "https://www.kaine.senate.gov/contact",
      "website": "http://www.kaine.senate.gov/",
      "class": "Class I",
      "bioguide_id": "K000384"
    },
    {
      "member_full": "Kennedy (R-LA)",
      "last_name": "Kennedy",
      "first_name": "John",
      "party": "R",
      "state": "LA",
      "address": "B11 Russell Senate Office Building",
      "phone": "(202) 224-4623",
      "email": "https://www.kennedy.senate.gov/content/contact-senator",
      "website": "http://www.kennedy.senate.gov",
      "class": "Class III",
      "bioguide_id": "K000393"
    },
    {
      "member_full": "King (I-ME)",
      "last_name": "King",
      "first_name": "Angus S., Jr.",
      "party": "I",
      "state": "ME",
      "address": "133 Hart Senate Office Building",
      "phone": "(202) 224-5344",
      "email": "https://www.king.senate.gov/contact",
      "website": "http://www.king.senate.gov/",
      "class": "Class I",
      "bioguide_id": "K000383"
    },
    {
      "member_full": "Klobuchar (D-MN)",
      "last_name": "Klobuchar",
      "first_name": "Amy",
      "party": "D",
      "state": "MN",
      "address": "302 Hart Senate Office Building",
      "phone": "(202) 224-3244",
      "email": "http://www.klobuchar.senate.gov/public/index.cfm/contact",
      "website": "http://www.klobuchar.senate.gov/",
      "class": "Class I",
      "bioguide_id": "K000367"
    },
    {
      "member_full": "Lankford (R-OK)",
      "last_name": "Lankford",
      "first_name": "James",
      "party": "R",
      "state": "OK",
      "address": "316 Hart Senate Office Building",
      "phone": "(202) 224-5754",
      "email": "http://www.lankford.senate.gov/contact/email",
      "website": "http://www.lankford.senate.gov",
      "class": "Class III",
      "bioguide_id": "L000575"
    },
    {
      "member_full": "Leahy (D-VT)",
      "last_name": "Leahy",
      "first_name": "Patrick J.",
      "party": "D",
      "state": "VT",
      "address": "437 Russell Senate Office Building",
      "phone": "(202) 224-4242",
      "email": "https://www.leahy.senate.gov/contact/",
      "website": "http://www.leahy.senate.gov/",
      "class": "Class III",
      "bioguide_id": "L000174"
    },
    {
      "member_full": "Lee (R-UT)",
      "last_name": "Lee",
      "first_name": "Mike",
      "party": "R",
      "state": "UT",
      "address": "361A Russell Senate Office Building",
      "phone": "(202) 224-5444",
      "email": "https://www.lee.senate.gov/public/index.cfm/contact",
      "website": "http://www.lee.senate.gov/",
      "class": "Class III",
      "bioguide_id": "L000577"
    },
    {
      "member_full": "Manchin (D-WV)",
      "last_name": "Manchin",
      "first_name": "Joe, III",
      "party": "D",
      "state": "WV",
      "address": "306 Hart Senate Office Building",
      "phone": "(202) 224-3954",
      "email": "http://www.manchin.senate.gov/public/index.cfm/contact-form",
      "website": "http://www.manchin.senate.gov/",
      "class": "Class I",
      "bioguide_id": "M001183"
    },
    {
      "member_full": "Markey (D-MA)",
      "last_name": "Markey",
      "first_name": "Edward J.",
      "party": "D",
      "state": "MA",
      "address": "255 Dirksen Senate Office Building",
      "phone": "(202) 224-2742",
      "email": "https://www.markey.senate.gov/contact",
      "website": "http://www.markey.senate.gov/",
      "class": "Class II",
      "bioguide_id": "M000133"
    },
    {
      "member_full": "McCain (R-AZ)",
      "last_name": "McCain",
      "first_name": "John",
      "party": "R",
      "state": "AZ",
      "address": "218 Russell Senate Office Building",
      "phone": "(202) 224-2235",
      "email": "https://www.mccain.senate.gov/public/index.cfm/contact-form",
      "website": "http://www.mccain.senate.gov/",
      "class": "Class III",
      "bioguide_id": "M000303"
    },
    {
      "member_full": "McCaskill (D-MO)",
      "last_name": "McCaskill",
      "first_name": "Claire",
      "party": "D",
      "state": "MO",
      "address": "730 Hart Senate Office Building",
      "phone": "(202) 224-6154",
      "email": "http://www.mccaskill.senate.gov/contact",
      "website": "http://www.mccaskill.senate.gov/",
      "class": "Class I",
      "bioguide_id": "M001170"
    },
    {
      "member_full": "McConnell (R-KY)",
      "last_name": "McConnell",
      "first_name": "Mitch",
      "party": "R",
      "state": "KY",
      "address": "317 Russell Senate Office Building",
      "phone": "(202) 224-2541",
      "email": "http://www.mcconnell.senate.gov/public/index.cfm?p=contact",
      "website": "http://www.mcconnell.senate.gov/",
      "class": "Class II",
      "bioguide_id": "M000355",
      "leadership_position": "Majority Leader"
    },
    {
      "member_full": "Menendez (D-NJ)",
      "last_name": "Menendez",
      "first_name": "Robert",
      "party": "D",
      "state": "NJ",
      "address": "528 Hart Senate Office Building",
      "phone": "(202) 224-4744",
      "email": "https://www.menendez.senate.gov/contact",
      "website": "http://www.menendez.senate.gov/",
      "class": "Class I",
      "bioguide_id": "M000639"
    },
    {
      "member_full": "Merkley (D-OR)",
      "last_name": "Merkley",
      "first_name": "Jeff",
      "party": "D",
      "state": "OR",
      "address": "313 Hart Senate Office Building",
      "phone": "(202) 224-3753",
      "email": "http://www.merkley.senate.gov/contact/",
      "website": "http://www.merkley.senate.gov",
      "class": "Class II",
      "bioguide_id": "M001176"
    },
    {
      "member_full": "Moran (R-KS)",
      "last_name": "Moran",
      "first_name": "Jerry",
      "party": "R",
      "state": "KS",
      "address": "521 Dirksen Senate Office Building",
      "phone": "(202) 224-6521",
      "email": "https://www.moran.senate.gov/public/index.cfm/e-mail-jerry",
      "website": "http://www.moran.senate.gov",
      "class": "Class III",
      "bioguide_id": "M000934"
    },
    {
      "member_full": "Murkowski (R-AK)",
      "last_name": "Murkowski",
      "first_name": "Lisa",
      "party": "R",
      "state": "AK",
      "address": "522 Hart Senate Office Building",
      "phone": "(202) 224-6665",
      "email": "https://www.murkowski.senate.gov/public/index.cfm/contact",
      "website": "http://www.murkowski.senate.gov/",
      "class": "Class III",
      "bioguide_id": "M001153"
    },
    {
      "member_full": "Murphy (D-CT)",
      "last_name": "Murphy",
      "first_name": "Christopher",
      "party": "D",
      "state": "CT",
      "address": "136 Hart Senate Office Building",
      "phone": "(202) 224-4041",
      "email": "http://www.murphy.senate.gov/contact",
      "website": "http://www.murphy.senate.gov/",
      "class": "Class I",
      "bioguide_id": "M001169"
    },
    {
      "member_full": "Murray (D-WA)",
      "last_name": "Murray",
      "first_name": "Patty",
      "party": "D",
      "state": "WA",
      "address": "154 Russell Senate Office Building",
      "phone": "(202) 224-2621",
      "email": "http://www.murray.senate.gov/public/index.cfm/contactme",
      "website": "http://www.murray.senate.gov/",
      "class": "Class III",
      "bioguide_id": "M001111",
      "leadership_position": "Assistant Democratic Leader"
    },
    {
      "member_full": "Nelson (D-FL)",
      "last_name": "Nelson",
      "first_name": "Bill",
      "party": "D",
      "state": "FL",
      "address": "716 Hart Senate Office Building",
      "phone": "(202) 224-5274",
      "email": "https://www.billnelson.senate.gov/contact-bill",
      "website": "http://www.billnelson.senate.gov/",
      "class": "Class I",
      "bioguide_id": "N000032"
    },
    {
      "member_full": "Paul (R-KY)",
      "last_name": "Paul",
      "first_name": "Rand",
      "party": "R",
      "state": "KY",
      "address": "167 Russell Senate Office Building",
      "phone": "(202) 224-4343",
      "email": "https://www.paul.senate.gov/connect/email-rand",
      "website": "http://www.paul.senate.gov",
      "class": "Class III",
      "bioguide_id": "P000603"
    },
    {
      "member_full": "Perdue (R-GA)",
      "last_name": "Perdue",
      "first_name": "David",
      "party": "R",
      "state": "GA",
      "address": "383 Russell Senate Office Building",
      "phone": "(202) 224-3521",
      "email": "https://www.perdue.senate.gov/connect/email",
      "website": "http://www.perdue.senate.gov",
      "class": "Class II",
      "bioguide_id": "P000612"
    },
    {
      "member_full": "Peters (D-MI)",
      "last_name": "Peters",
      "first_name": "Gary C.",
      "party": "D",
      "state": "MI",
      "address": "724 Hart Senate Office Building",
      "phone": "(202) 224-6221",
      "email": "https://www.peters.senate.gov/contact/email-gary",
      "website": "http://www.peters.senate.gov",
      "class": "Class II",
      "bioguide_id": "P000595"
    },
    {
      "member_full": "Portman (R-OH)",
      "last_name": "Portman",
      "first_name": "Rob",
      "party": "R",
      "state": "OH",
      "address": "448 Russell Senate Office Building",
      "phone": "(202) 224-3353",
      "email": "https://www.portman.senate.gov/public/index.cfm/contact?p=contact-form",
      "website": "http://www.portman.senate.gov",
      "class": "Class III",
      "bioguide_id": "P000449"
    },
    {
      "member_full": "Reed (D-RI)",
      "last_name": "Reed",
      "first_name": "Jack",
      "party": "D",
      "state": "RI",
      "address": "728 Hart Senate Office Building",
      "phone": "(202) 224-4642",
      "email": "https://www.reed.senate.gov/contact/",
      "website": "http://www.reed.senate.gov/",
      "class": "Class II",
      "bioguide_id": "R000122"
    },
    {
      "member_full": "Risch (R-ID)",
      "last_name": "Risch",
      "first_name": "James E.",
      "party": "R",
      "state": "ID",
      "address": "483 Russell Senate Office Building",
      "phone": "(202) 224-2752",
      "email": "http://www.risch.senate.gov/public/index.cfm?p=Email",
      "website": "http://www.risch.senate.gov",
      "class": "Class II",
      "bioguide_id": "R000584"
    },
    {
      "member_full": "Roberts (R-KS)",
      "last_name": "Roberts",
      "first_name": "Pat",
      "party": "R",
      "state": "KS",
      "address": "109 Hart Senate Office Building",
      "phone": "(202) 224-4774",
      "email": "https://www.roberts.senate.gov/public/?p=EmailPat",
      "website": "http://www.roberts.senate.gov/",
      "class": "Class II",
      "bioguide_id": "R000307"
    },
    {
      "member_full": "Rounds (R-SD)",
      "last_name": "Rounds",
      "first_name": "Mike",
      "party": "R",
      "state": "SD",
      "address": "502 Hart Senate Office Building",
      "phone": "(202) 224-5842",
      "email": "https://www.rounds.senate.gov/contact/email-mike",
      "website": "http://www.rounds.senate.gov",
      "class": "Class II",
      "bioguide_id": "R000605"
    },
    {
      "member_full": "Rubio (R-FL)",
      "last_name": "Rubio",
      "first_name": "Marco",
      "party": "R",
      "state": "FL",
      "address": "284 Russell Senate Office Building",
      "phone": "(202) 224-3041",
      "email": "http://www.rubio.senate.gov/public/index.cfm/contact",
      "website": "http://www.rubio.senate.gov",
      "class": "Class III",
      "bioguide_id": "R000595"
    },
    {
      "member_full": "Sanders (I-VT)",
      "last_name": "Sanders",
      "first_name": "Bernard",
      "party": "I",
      "state": "VT",
      "address": "332 Dirksen Senate Office Building",
      "phone": "(202) 224-5141",
      "email": "http://www.sanders.senate.gov/contact/",
      "website": "http://www.sanders.senate.gov/",
      "class": "Class I",
      "bioguide_id": "S000033"
    },
    {
      "member_full": "Sasse (R-NE)",
      "last_name": "Sasse",
      "first_name": "Ben",
      "party": "R",
      "state": "NE",
      "address": "386A Russell Senate Office Building",
      "phone": "(202) 224-4224",
      "email": "http://www.sasse.senate.gov/public/index.cfm/email-ben",
      "website": "http://www.sasse.senate.gov",
      "class": "Class II",
      "bioguide_id": "S001197"
    },
    {
      "member_full": "Schatz (D-HI)",
      "last_name": "Schatz",
      "first_name": "Brian",
      "party": "D",
      "state": "HI",
      "address": "722 Hart Senate Office Building",
      "phone": "(202) 224-3934",
      "email": "https://www.schatz.senate.gov/contact",
      "website": "http://www.schatz.senate.gov",
      "class": "Class III",
      "bioguide_id": "S001194"
    },
    {
      "member_full": "Schumer (D-NY)",
      "last_name": "Schumer",
      "first_name": "Charles E.",
      "party": "D",
      "state": "NY",
      "address": "322 Hart Senate Office Building",
      "phone": "(202) 224-6542",
      "email": "https://www.schumer.senate.gov/contact/email-chuck",
      "website": "http://www.schumer.senate.gov/",
      "class": "Class III",
      "bioguide_id": "S000148",
      "leadership_position": "Democratic Leader"
    },
    {
      "member_full": "Scott (R-SC)",
      "last_name": "Scott",
      "first_name": "Tim",
      "party": "R",
      "state": "SC",
      "address": "717 Hart Senate Office Building",
      "phone": "(202) 224-6121",
      "email": "https://www.scott.senate.gov/contact/email-me",
      "website": "http://www.scott.senate.gov/",
      "class": "Class III",
      "bioguide_id": "S001184"
    },
    {
      "member_full": "Shaheen (D-NH)",
      "last_name": "Shaheen",
      "first_name": "Jeanne",
      "party": "D",
      "state": "NH",
      "address": "506 Hart Senate Office Building",
      "phone": "(202) 224-2841",
      "email": "https://www.shaheen.senate.gov/contact/contact-jeanne",
      "website": "http://www.shaheen.senate.gov",
      "class": "Class II",
      "bioguide_id": "S001181"
    },
    {
      "member_full": "Shelby (R-AL)",
      "last_name": "Shelby",
      "first_name": "Richard C.",
      "party": "R",
      "state": "AL",
      "address": "304 Russell Senate Office Building",
      "phone": "(202) 224-5744",
      "email": "https://www.shelby.senate.gov/public/index.cfm/emailsenatorshelby",
      "website": "http://www.shelby.senate.gov/",
      "class": "Class III",
      "bioguide_id": "S000320"
    },
    {
      "member_full": "Strange (R-AL)",
      "last_name": "Strange",
      "first_name": "Luther",
      "party": "R",
      "state": "AL",
      "address": "G-12 Dirksen Senate Office Building",
      "phone": "(202) 224-4124",
      "email": [],
      "website": "https://www.senate.gov/senators/115thCongress/Luther_Strange.htm",
      "class": "Class II",
      "bioguide_id": "S001202"
    },
    {
      "member_full": "Stabenow (D-MI)",
      "last_name": "Stabenow",
      "first_name": "Debbie",
      "party": "D",
      "state": "MI",
      "address": "731 Hart Senate Office Building",
      "phone": "(202) 224-4822",
      "email": "http://www.stabenow.senate.gov/?p=contact",
      "website": "http://www.stabenow.senate.gov/",
      "class": "Class I",
      "bioguide_id": "S000770"
    },
    {
      "member_full": "Sullivan (R-AK)",
      "last_name": "Sullivan",
      "first_name": "Dan",
      "party": "R",
      "state": "AK",
      "address": "702 Hart Senate Office Building",
      "phone": "(202) 224-3004",
      "email": "https://www.sullivan.senate.gov/contact/email",
      "website": "http://www.sullivan.senate.gov",
      "class": "Class II",
      "bioguide_id": "S001198"
    },
    {
      "member_full": "Tester (D-MT)",
      "last_name": "Tester",
      "first_name": "Jon",
      "party": "D",
      "state": "MT",
      "address": "311 Hart Senate Office Building",
      "phone": "(202) 224-2644",
      "email": "https://www.tester.senate.gov/?p=email_senator",
      "website": "http://www.tester.senate.gov/",
      "class": "Class I",
      "bioguide_id": "T000464"
    },
    {
      "member_full": "Thune (R-SD)",
      "last_name": "Thune",
      "first_name": "John",
      "party": "R",
      "state": "SD",
      "address": "511 Dirksen Senate Office Building",
      "phone": "(202) 224-2321",
      "email": "http://www.thune.senate.gov/public/index.cfm/contact",
      "website": "http://www.thune.senate.gov/",
      "class": "Class III",
      "bioguide_id": "T000250"
    },
    {
      "member_full": "Tillis (R-NC)",
      "last_name": "Tillis",
      "first_name": "Thom",
      "party": "R",
      "state": "NC",
      "address": "185 Dirksen Senate Office Building",
      "phone": "(202) 224-6342",
      "email": "https://www.tillis.senate.gov/public/index.cfm/email-me",
      "website": "http://www.tillis.senate.gov",
      "class": "Class II",
      "bioguide_id": "T000476"
    },
    {
      "member_full": "Toomey (R-PA)",
      "last_name": "Toomey",
      "first_name": "Patrick J.",
      "party": "R",
      "state": "PA",
      "address": "248 Russell Senate Office Building",
      "phone": "(202) 224-4254",
      "email": "https://www.toomey.senate.gov/?p=contact",
      "website": "http://www.toomey.senate.gov/",
      "class": "Class III",
      "bioguide_id": "T000461"
    },
    {
      "member_full": "Udall (D-NM)",
      "last_name": "Udall",
      "first_name": "Tom",
      "party": "D",
      "state": "NM",
      "address": "531 Hart Senate Office Building",
      "phone": "(202) 224-6621",
      "email": "https://www.tomudall.senate.gov/?p=contact",
      "website": "http://www.tomudall.senate.gov",
      "class": "Class II",
      "bioguide_id": "U000039"
    },
    {
      "member_full": "Van Hollen (D-MD)",
      "last_name": "Van Hollen",
      "first_name": "Chris",
      "party": "D",
      "state": "MD",
      "address": "B40C Dirksen Senate Office Building",
      "phone": "(202) 224-4654",
      "email": "https://www.vanhollen.senate.gov/content/contact-senator",
      "website": "http://www.vanhollen.senate.gov",
      "class": "Class III",
      "bioguide_id": "V000128"
    },
    {
      "member_full": "Warner (D-VA)",
      "last_name": "Warner",
      "first_name": "Mark R.",
      "party": "D",
      "state": "VA",
      "address": "475 Russell Senate Office Building",
      "phone": "(202) 224-2023",
      "email": "http://www.warner.senate.gov/public/index.cfm?p=Contact",
      "website": "http://www.warner.senate.gov",
      "class": "Class II",
      "bioguide_id": "W000805"
    },
    {
      "member_full": "Warren (D-MA)",
      "last_name": "Warren",
      "first_name": "Elizabeth",
      "party": "D",
      "state": "MA",
      "address": "317 Hart Senate Office Building",
      "phone": "(202) 224-4543",
      "email": "https://www.warren.senate.gov/?p=email_senator",
      "website": "http://www.warren.senate.gov",
      "class": "Class I",
      "bioguide_id": "W000817"
    },
    {
      "member_full": "Whitehouse (D-RI)",
      "last_name": "Whitehouse",
      "first_name": "Sheldon",
      "party": "D",
      "state": "RI",
      "address": "530 Hart Senate Office Building",
      "phone": "(202) 224-2921",
      "email": "https://www.whitehouse.senate.gov/contact/email-sheldon",
      "website": "http://www.whitehouse.senate.gov/",
      "class": "Class I",
      "bioguide_id": "W000802"
    },
    {
      "member_full": "Wicker (R-MS)",
      "last_name": "Wicker",
      "first_name": "Roger F.",
      "party": "R",
      "state": "MS",
      "address": "555 Dirksen Senate Office Building",
      "phone": "(202) 224-6253",
      "email": "https://www.wicker.senate.gov/public/index.cfm/contact",
      "website": "http://www.wicker.senate.gov",
      "class": "Class I",
      "bioguide_id": "W000437"
    },
    {
      "member_full": "Wyden (D-OR)",
      "last_name": "Wyden",
      "first_name": "Ron",
      "party": "D",
      "state": "OR",
      "address": "221 Dirksen Senate Office Building",
      "phone": "(202) 224-5244",
      "email": "https://www.wyden.senate.gov/contact/",
      "website": "http://www.wyden.senate.gov/",
      "class": "Class III",
      "bioguide_id": "W000779"
    },
    {
      "member_full": "Young (R-IN)",
      "last_name": "Young",
      "first_name": "Todd",
      "party": "R",
      "state": "IN",
      "address": "B33 Russell Senate Office Building",
      "phone": "(202) 224-5623",
      "email": "https://www.young.senate.gov/content/contact-senator",
      "website": "http://www.young.senate.gov",
      "class": "Class III",
      "bioguide_id": "Y000064"
    }
  ]

module.exports = senators;